pipeline{
    agent any

    stages{
        stage('Build project'){
            steps{
                echo "===== Building project ====="
                sh "cd stockTradingSystem"
                sh "mvn clean package -DskipTests=true"
            }
        }
        stage('Build docker image'){
            steps{
                echo "===== Building docker file ====="
                sh "docker build -t stock-trading-app ."
                sh "docker tag stock-trading-app shubhpatel14/stock-trading-app"
            }
        }
    }
    post{
        always{
            echo "Stock trading application Job done!"
        }
    }
}